### ISSUE TITLE
Gantry needs to be able to use hosts/hostgroups defined in the gantryfile

### ISSUE THREAD

**Issue by bitemyapp** [drsnyder/gantry#1]
Been using gantry, would like to be able to stop using Fabric.

Really need the ability to just define a host list for given role.

http://docs.fabfile.org/en/1.6/usage/execution.html#defining-host-lists

**Comment by drsnyder** [comment]
This can be done in the gantry file like so:

```
(task app
 (update-config :resource 
                (-> (create-resource) 
                  (add "app003.site.com") 
                  (add "app005.site.com") 
                  (add "app006.site.com"))))

(task uptime
    (run "uptime"))
```

Then you can run:

```
gantry -f gantryfile -t db,uptime
```

Does that address your issue?

**Comment by bitemyapp** [comment]
Not quite, it doesn't allow me to assign per task hosts as far as I can tell. Is there a way to do that?

**Comment by drsnyder** [comment]
Ok, I see. Let me investigate.

**Comment by bitemyapp** [comment]
Thank you very much! On a side note, I edited the gantry runner to use drip instead of java, made startup time much faster. If you're not already doing so, you should try it.

**Comment by drsnyder** [comment]
Thanks for your patience. Gantry is quite a bit out of date-- it was last built with clojure 1.2.0. I'm going to bring it up to 1.5.1 and take a look at this issue.
